name: hifigan2
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - tensorboard
  - numpy
  - scipy
  - matplotlib
  - librosa
  - numba

